#!/bin/bash

#Custermize this for your application
APPLICATION_FILE_PATH=bin/mondoo

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/mondoo

# Install Launchd:
echo "Installing launchd service"
cp ${PRODUCT_HOME}/etc/com.mondoo.client.plist /Library/LaunchDaemons/
launchctl load /Library/LaunchDaemons/com.mondoo.client.plist

# Do not automatically start client, to start run: 
# sudo launchctl start com.mondoo.client
# sudo launchctl enable system/com.mondoo.client
echo "Post installation process finished"
