name: Build MacOS Package for cnquery

on:
  push:
    branches:
      - main

env:
  CNQUERY_VERSION: '6.18.0-alpha2'

jobs:
  pkg:
    name: 'Packaging: Mac'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install mitchellh/gon
        run: brew install mitchellh/gon/gon
      - name: Put binaries in dist/macos
        run: |
          pwd && env  # For debugging
          mkdir -p dist/macos/ 
          cd ${GITHUB_WORKSPACE}/dist/macos/
          mkdir mac_darwin_amd64 && cd mac_darwin_amd64
          # curl doesn't work because the repo is currently private, fake it on cuddletech
          #curl -L https://github.com/mondoohq/cnquery/releases/download/v${{ env.CNQUERY_VERSION}}/cnquery_${{env.CNQUERY_VERSION}}_darwin_amd64.tar.gz | tar xfvz -
          curl -sL https://files.cuddletech.com/mondoohq/cnquery/releases/download/v${{ env.CNQUERY_VERSION}}/cnquery_${{env.CNQUERY_VERSION}}_darwin_amd64.tar.gz | tar xfvz -
          cd ${GITHUB_WORKSPACE}/dist/macos/
          mkdir mac_darwin_arm64 && cd mac_darwin_arm64
          curl -sL https://files.cuddletech.com/mondoohq/cnquery/releases/download/v${{ env.CNQUERY_VERSION}}/cnquery_${{env.CNQUERY_VERSION}}_darwin_arm64.tar.gz | tar xfvz -   
      - name: Setup keychain for signing certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_INSTALLER }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PW }}
      - name: Run Mac Packager
        run: |
          pwd
          ls -lR
          ${GITHUB_WORKSPACE}/scripts/mac/build-pkg.sh ${{ env.CNQUERY_VERSION }}
      - name: Inspect
        if: ${{ always() }}
        run: ls -lR

