name: Keychain Test Action

on:
  workflow_dispatch:  

env:
  CNQUERY_VERSION: '6.18.0-alpha2'

jobs:
  pkg:
    name: 'Key Setup'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup keychain for signing certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_INSTALLER }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PW }}
      - name: Show Security Identities
        run: |
          security find-identity -v
      - name: Codesign executable
        run: |
          curl -O https://releases.mondoo.io/cnquery/7.0.0-alpha1/cnquery_7.0.0-alpha1_darwin_amd64.tar.gz
          tar xfvz cnquery_7.0.0-alpha1_darwin_amd64.tar.gz
          codesign -s "Developer ID Installer: Mondoo, Inc. (W2KUBWKG84)" -f -v --timestamp --options runtime ./cnquery


